jhoanssierramt/reto1ciclo4

- ciclo4/nbactions.xml
- ciclo4/pom.xml
- ciclo4/src/main/java/co/edu/usa/ciclo4/modelo/User.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/repositorio/UserRepostory.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/repositorio/crud/UserCrudRepository.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/servicio/UserService.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/web/UserController.java
- ciclo4/src/main/resources/application-dev.properties
- ciclo4/src/main/resources/application-h2.properties
- ciclo4/src/main/resources/application-prod.properties
- ciclo4/src/main/resources/application.properties
Por Favor Combinar Cambios Reto1
> Creacion Modelo User

- ciclo4/src/main/java/co/edu/usa/ciclo4/Ciclo4Application.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/modelo/User.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/repositorio/UserRepository.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/repositorio/crud/UserCrudRepository.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/servicio/UserService.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/web/UserController.java
> Final Backend

- ciclo4/nbactions.xml
- ciclo4/src/main/resources/static/home.html
- ciclo4/src/main/resources/static/index.html
- ciclo4/src/main/resources/static/js/login.js
- ciclo4/src/main/resources/static/style/login.css
> avance frontend

- ciclo4/src/main/resources/static/home.html
- ciclo4/src/main/resources/static/index.html
- ciclo4/src/main/resources/static/js/home.js
- ciclo4/src/main/resources/static/js/login.js
- ciclo4/src/main/resources/static/style/home.css
> Resolución de conflicto y avance Login

- ciclo4/src/main/resources/static/index.html
- ciclo4/src/main/resources/static/js/login.js
> creacion de modal registro

- ciclo4/nbactions.xml
- ciclo4/src/main/resources/application-dev.properties
- ciclo4/src/main/resources/static/index.html
- ciclo4/src/main/resources/static/js/login.js
- ciclo4/src/main/resources/static/style/home.css
> solucion modal

- ciclo4/nbactions.xml
- ciclo4/src/main/resources/application-dev.properties
- ciclo4/src/main/resources/static/index.html
- ciclo4/src/main/resources/static/js/login.js
>  Finalizacion Reto 1

- ciclo4/nbactions.xml
- ciclo4/src/main/resources/application-dev.properties
- ciclo4/src/main/resources/static/index.html
- ciclo4/src/main/resources/static/js/login.js
> correción formulario registro

- ciclo4/pom.xml
- ciclo4/src/main/java/co/edu/usa/ciclo4/modelo/User.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/repositorio/UserRepository.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/repositorio/crud/UserCrudRepository.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/servicio/UserService.java
- ciclo4/src/main/resources/application-dev.properties
- ciclo4/src/main/resources/application.properties
> conexion con  MongoDB

- ciclo4/nbactions.xml
- ciclo4/src/main/java/co/edu/usa/ciclo4/Ciclo4Application.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/modelo/Accessory.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/modelo/User.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/repositorio/AccessoryRepository.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/repositorio/UserRepository.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/repositorio/crud/AccessoryCrudRepository.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/repositorio/crud/UserCrudRepository.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/servicio/AccessoryService.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/servicio/UserService.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/web/AccessoryController.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/web/UserController.java
- ciclo4/src/main/resources/application-dev.properties
- ciclo4/src/main/resources/application.properties
> Creacion de entidade Accessory

- ciclo4/src/main/java/co/edu/usa/ciclo4/modelo/Accessory.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/modelo/User.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/repositorio/AccessoryRepository.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/repositorio/UserRepository.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/repositorio/crud/AccessoryCrudRepository.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/repositorio/crud/UserCrudRepository.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/servicio/AccessoryService.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/servicio/UserService.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/web/AccessoryController.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/web/UserController.java
- ciclo4/src/main/resources/application.properties
> backend reto 2 (con pruebas funcionando)

- ciclo4/src/main/resources/static/js/home.js
- ciclo4/src/main/resources/static/js/login.js
Cuando el usuario no se encontraba pasaba a home con id=null
> arreglar logIn

- ciclo4/src/main/java/co/edu/usa/ciclo4/Ciclo4Application.java
- ciclo4/src/main/resources/application.properties
- frontEnd/admin.html
- frontEnd/index.html
- frontEnd/js/admin.js
- frontEnd/js/login.js
> EDITAR Y ELIMINAR USUARIO

- ciclo4/src/main/resources/application.properties
- frontEnd/admin.html
- frontEnd/js/admin.js
> INIT TABLA ACCESORIOS

- ciclo4/src/main/resources/application.properties
- frontEnd/admin.html
- frontEnd/js/admin.js
- frontEnd/js/adminAccessory.js
- frontEnd/js/login.js
> frontEnd de productos: Falta poner el logo y lo del radio button

- .vscode/launch.json
- ciclo4/src/main/java/co/edu/usa/ciclo4/modelo/Order.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/modelo/User.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/repositorio/OrderRepository.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/repositorio/crud/OrderCrudRepository.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/servicio/OrderService.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/web/OrderController.java
- ciclo4/src/main/resources/application.properties
- frontEnd/admin.html
- frontEnd/home.html
- frontEnd/index.html
Se agregan los servicios solicitados en reto 3, se ajustan rutas en archivos html.
> Add servicios order , se ajustan rutas de html

- ciclo4/src/main/java/co/edu/usa/ciclo4/modelo/Order.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/servicio/OrderService.java
- frontEnd/admin.html
- frontEnd/home.html
- frontEnd/js/home.js
- frontEnd/js/homeOrder.js
- frontEnd/js/login.js
- frontEnd/style/home.css
Se crea archivo homeOrder.js encargado de gestionar funciones orden de pedido
> se crean funciones para orden de pedido front

- frontEnd/home.html
- frontEnd/js/home.js
- frontEnd/js/homeOrder.js
se completan funciones para crear de orden, sesion grupal 11 diciembre
> se completan funciones para crear de orden

- ciclo4/src/main/java/co/edu/usa/ciclo4/repositorio/UserRepository.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/repositorio/crud/UserCrudRepository.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/servicio/UserService.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/web/UserController.java
- frontEnd/admin.html
- frontEnd/home.html
- frontEnd/js/admin.js
- frontEnd/js/home.js
- frontEnd/js/homeOrder.js
- frontEnd/js/login.js
> Fin asesor frontEnd

- ciclo4/src/main/java/co/edu/usa/ciclo4/modelo/User.java
- frontEnd/home.html
- frontEnd/js/home.js
- frontEnd/js/homeCoord.js
> Fin fronEnd Coordinador

- ciclo4/src/main/java/co/edu/usa/ciclo4/modelo/User.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/servicio/UserService.java
- frontEnd/admin.html
- frontEnd/home.html
- frontEnd/index.html
- frontEnd/js/admin.js
- frontEnd/js/home.js
- frontEnd/js/login.js
> Fin Reto 3

- ciclo4/src/main/java/co/edu/usa/ciclo4/Ciclo4Application.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/repositorio/OrderRepository.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/repositorio/crud/OrderCrudRepository.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/servicio/OrderService.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/web/OrderController.java
> Fin Backend Reto4

- ciclo4/src/main/java/co/edu/usa/ciclo4/repositorio/AccessoryRepository.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/repositorio/UserRepository.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/servicio/AccessoryService.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/servicio/UserService.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/web/AccessoryController.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/web/UserController.java
> FINAL ENDPOINTS RETO5

- ciclo4/src/main/java/co/edu/usa/ciclo4/web/OrderController.java
> Error de TimeZones ARREGLADO!

- react/ciclo4_g9_subg2/src/components/Home/Home.js
- react/ciclo4_g9_subg2/src/components/birthday/Birthday.js
> Modulo de cumpleaños finalizado

- ciclo4/src/main/java/co/edu/usa/ciclo4/repositorio/AccessoryRepository.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/repositorio/UserRepository.java
- ciclo4/src/main/java/co/edu/usa/ciclo4/repositorio/crud/AccessoryCrudRepository.java
- react/ciclo4_g9_subg2/package-lock.json
- react/ciclo4_g9_subg2/package.json
- react/ciclo4_g9_subg2/src/components/Home/Home.js
- react/ciclo4_g9_subg2/src/components/Home/home.css
- react/ciclo4_g9_subg2/src/components/Login/LoginFunc.js
- react/ciclo4_g9_subg2/src/components/Login/login.css
- react/ciclo4_g9_subg2/src/components/birthday/Birthday.js
- react/ciclo4_g9_subg2/src/components/detail-order/DetailOrder.js
- react/ciclo4_g9_subg2/src/components/orders/Orders.js
- react/ciclo4_g9_subg2/src/components/products/Products.js
- react/ciclo4_g9_subg2/src/components/userEdit/UserEdit.js
- react/ciclo4_g9_subg2/src/context/GlobalSession.js
> Fin frontEnd Reto 5

- ciclo4/src/main/java/co/edu/usa/ciclo4/repositorio/UserRepository.java
> Fix buenas prácticas UserRepository
